set search_path to app;


CREATE TABLE app.club
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name           VARCHAR(250)                            NOT NULL,
    crest_image_id VARCHAR(250),
    CONSTRAINT pk_club PRIMARY KEY (id)
);


CREATE TABLE app.stadium
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    club_id BIGINT,
    name    VARCHAR(250)                            NOT NULL,
    CONSTRAINT pk_stadium PRIMARY KEY (id),
    CONSTRAINT FK_STADIUM_ON_CLUB FOREIGN KEY (club_id) REFERENCES app.club (id)
);


CREATE TABLE app.stand
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    stadium_id BIGINT,
    name       VARCHAR(250)                            NOT NULL,
    capacity   INTEGER                                 NOT NULL,
    CONSTRAINT pk_stand PRIMARY KEY (id),
    CONSTRAINT FK_STAND_ON_STADIUM FOREIGN KEY (stadium_id) REFERENCES app.stadium (id)
);


CREATE TABLE app.match
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    home_team_id BIGINT                                  NOT NULL,
    away_team_id BIGINT                                  NOT NULL,
    stadium_id   BIGINT                                  NOT NULL,
    start_time   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_match PRIMARY KEY (id),
    CONSTRAINT FK_MATCH_ON_AWAY_TEAM FOREIGN KEY (away_team_id) REFERENCES app.club (id),
    CONSTRAINT FK_MATCH_ON_HOME_TEAM FOREIGN KEY (home_team_id) REFERENCES app.club (id),
    CONSTRAINT FK_MATCH_ON_STADIUM FOREIGN KEY (stadium_id) REFERENCES app.stadium (id)
);


CREATE TABLE app.subscription
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id BIGINT                                  NOT NULL,
    club_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_subscription PRIMARY KEY (id),
    CONSTRAINT FK_SUBSCRIPTION_ON_CLUB FOREIGN KEY (club_id) REFERENCES app.club (id),
    CONSTRAINT FK_SUBSCRIPTION_ON_USER FOREIGN KEY (user_id) REFERENCES app."user" (id)
);
