set search_path to app;


CREATE TABLE app.club_admin
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id    BIGINT                                  NOT NULL,
    club_id    BIGINT                                  NOT NULL,
    start_date TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    end_date   TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_club_admin PRIMARY KEY (id),
    CONSTRAINT FK_CLUB_ADMIN_ON_CLUB FOREIGN KEY (club_id) REFERENCES app.club (id),
    CONSTRAINT FK_CLUB_ADMIN_ON_USER FOREIGN KEY (user_id) REFERENCES app."user" (id)
);


CREATE TABLE app.ticket_offer
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    posted_by  BIGINT                                  NOT NULL,
    match_id   BIGINT                                  NOT NULL,
    start_date TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    end_date   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    image_id   VARCHAR(255),
    CONSTRAINT pk_ticket_offer PRIMARY KEY (id),
    CONSTRAINT FK_TICKET_OFFER_ON_MATCH FOREIGN KEY (match_id) REFERENCES app.match (id),
    CONSTRAINT FK_TICKET_OFFER_ON_CLUB_ADMIN FOREIGN KEY (posted_by) REFERENCES app.club_admin (id)
);


CREATE TABLE app.ticket_type
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    ticket_offer_id BIGINT,
    stand_id        BIGINT                                  NOT NULL,
    price           DECIMAL                                 NOT NULL,
    CONSTRAINT pk_ticket_type PRIMARY KEY (id),
    CONSTRAINT FK_TICKET_TYPE_ON_STAND FOREIGN KEY (stand_id) REFERENCES app.stand (id),
    CONSTRAINT FK_TICKET_TYPE_ON_TICKET_OFFER FOREIGN KEY (ticket_offer_id) REFERENCES app.ticket_offer (id)
);


CREATE TABLE app.ticket_purchase
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    ticket_type_id BIGINT                                  NOT NULL,
    user_id        BIGINT                                  NOT NULL,
    payment_id     VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_ticket_purchase PRIMARY KEY (id),
    CONSTRAINT FK_TICKET_PURCHASE_ON_TICKET_TYPE FOREIGN KEY (ticket_type_id) REFERENCES app.ticket_type (id),
    CONSTRAINT FK_TICKET_PURCHASE_ON_USER FOREIGN KEY (user_id) REFERENCES app."user" (id)
);
