set search_path to app;


CREATE TABLE app.season_pass_offer
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    posted_by  BIGINT                                  NOT NULL,
    year       INTEGER                                 NOT NULL,
    season     INTEGER                                 NOT NULL,
    start_date TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    end_date   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    image_id   VARCHAR(255),
    CONSTRAINT pk_season_pass_offer PRIMARY KEY (id),
    CONSTRAINT FK_SEASON_PASS_OFFER_ON_CLUB_ADMIN FOREIGN KEY (posted_by) REFERENCES app.club_admin (id)
);


CREATE TABLE app.season_pass_type
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    season_pass_offer_id BIGINT                                  NOT NULL,
    stand_id            BIGINT                                  NOT NULL,
    price               DECIMAL                                 NOT NULL,
    CONSTRAINT pk_season_pass_type PRIMARY KEY (id),
    CONSTRAINT FK_SEASON_PASS_TYPE_ON_MEMBERSHIP_OFFER FOREIGN KEY (season_pass_offer_id) REFERENCES app.season_pass_offer (id),
    CONSTRAINT FK_SEASON_PASS_TYPE_ON_STAND FOREIGN KEY (stand_id) REFERENCES app.stand (id)
);


CREATE TABLE app.season_pass_holder
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id             BIGINT                                  NOT NULL,
    season_pass_type_id BIGINT                                  NOT NULL,
    payment_id          VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_season_pass_holder PRIMARY KEY (id),
    CONSTRAINT FK_SEASON_PASS_HOLDER_ON_SEASON_PASS_TYPE FOREIGN KEY (season_pass_type_id) REFERENCES app.season_pass_type (id),
    CONSTRAINT FK_SEASON_PASS_HOLDER_ON_USER FOREIGN KEY (user_id) REFERENCES app."user" (id)
);